version: "3.0"
services:
  # web-ui at:  http://172.24.0.2:16686/jaeger
  jaeger:
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    image: jaegertracing/all-in-one:1.10
    ports:
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"

  api:
    build: .
    working_dir: /code
    volumes:
    - .:/code
    links:
    - jaeger:jaeger
    ports:
    - "8443:443"
    environment:
      PYTHONPATH: .
      JAEGER_AGENT_HOST: jaeger
    entrypoint: ["python", "-m", "openapi"]
